name: Build Application and Deploy

on:
  # Triggers the workflow on push/merge to the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REACT_APP_GA_MEASUREMENT_ID: G-3T3DMGBBJ0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: 16.15
            cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build
